# Generated by Django 3.2.15 on 2022-11-10 09:42

import Capstone_Project2.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField(null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('profile', models.ImageField(null=True, upload_to='')),
                ('friend', models.FileField(null=True, upload_to='')),
                ('is_delete', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', enumchoicefield.fields.EnumChoiceField(default=None, enum_class=Capstone_Project2.models.item_type, max_length=7)),
                ('publish_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(max_length=255, null=True, upload_to='photos')),
                ('num_records', models.IntegerField(null=True)),
                ('top_10_tags', models.FileField(null=True, upload_to='')),
                ('comment', models.TextField(null=True)),
                ('is_delete', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('records_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('publish_date', models.DateTimeField(null=True)),
                ('if_complete', models.BooleanField(null=True)),
                ('comment', models.TextField(null=True)),
                ('rate', models.FloatField(null=True)),
                ('tag', models.CharField(max_length=25, null=True)),
                ('like', models.IntegerField(null=True)),
                ('othercomment', models.FileField(null=True, upload_to='')),
                ('privacy', enumchoicefield.fields.EnumChoiceField(default=Capstone_Project2.models.privacy(1), enum_class=Capstone_Project2.models.privacy, max_length=11)),
                ('is_delete', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='capstone_project_vue/src/assets')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Capstone_Project2.account')),
                ('genres', models.ManyToManyField(related_name='myGenres', to='Capstone_Project2.Genres')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='Capstone_Project2.account')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to='Capstone_Project2.Account')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_friend_request', models.BooleanField(blank=True, default=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('request_Time', models.DateTimeField(null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Capstone_Project2.account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Capstone_Project2.account')),
            ],
        ),
    ]
